<?php

namespace Database\Seeders\Support;

final class ExpandedLocationCatalog
{
    /**
     * @return array<string, array{name: string, places: array<int, array{0: string, 1: string}>}>
     */
    public static function countries(): array
    {
        return [
            'BA' => [
                'name' => 'Bosna i Hercegovina',
                'places' => self::bosniaAndHerzegovina(),
            ],
            'RS' => [
                'name' => 'Srbija',
                'places' => self::serbia(),
            ],
            'HR' => [
                'name' => 'Hrvatska',
                'places' => self::croatia(),
            ],
            'IT' => [
                'name' => 'Italija',
                'places' => self::italy(),
            ],
            'DE' => [
                'name' => 'Njemacka',
                'places' => self::germany(),
            ],
            'AT' => [
                'name' => 'Austrija',
                'places' => self::austria(),
            ],
            'ME' => [
                'name' => 'Crna Gora',
                'places' => self::montenegro(),
            ],
            'MK' => [
                'name' => 'Makedonija',
                'places' => self::northMacedonia(),
            ],
            'SI' => [
                'name' => 'Slovenija',
                'places' => self::slovenia(),
            ],
        ];
    }

    /**
     * @return array<int, array{0: string, 1: string}>
     */
    private static function bosniaAndHerzegovina(): array
    {
        return self::uniquePlaces([
            ['Sarajevo', 'city'],
            ['Banja Luka', 'city'],
            ['Mostar', 'city'],
            ['Tuzla', 'city'],
            ['Zenica', 'city'],
            ['Bijeljina', 'city'],
            ['Brcko', 'city'],
            ['Prijedor', 'city'],
            ['Doboj', 'city'],
            ['Cazin', 'town'],
            ['Zvornik', 'town'],
            ['Zivinice', 'town'],
            ['Bihac', 'city'],
            ['Gradacac', 'town'],
            ['Visoko', 'town'],
            ['Trebinje', 'city'],
            ['Gorazde', 'town'],
            ['Konjic', 'town'],
            ['Travnik', 'town'],
            ['Bugojno', 'town'],
            ['Livno', 'town'],
            ['Gracanica', 'town'],
            ['Srebrenik', 'town'],
            ['Tesanj', 'town'],
            ['Kakanj', 'town'],
            ['Kalesija', 'town'],
            ['Sanski Most', 'town'],
            ['Foca', 'town'],
            ['Jajce', 'town'],
            ['Nevesinje', 'town'],
            ['Siroki Brijeg', 'town'],
            ['Capljina', 'town'],
            ['Lukavac', 'town'],
            ['Maglaj', 'town'],
            ['Bosanska Krupa', 'town'],
            ['Velika Kladusa', 'town'],
            ['Ilidza', 'town'],
            ['Pale', 'town'],
            ['Sokolac', 'town'],
            ['Rogatica', 'town'],
            ['Posusje', 'town'],
            ['Tomislavgrad', 'town'],
            ['Kiseljak', 'town'],
            ['Vitez', 'town'],
            ['Busovaca', 'town'],
            ['Fojnica', 'town'],
            ['Jelah', 'village'],
            ['Kiseljak (Tesanj)', 'village'],
            ['Maoca', 'village'],
            ['Ahmici', 'village'],
            ['Pocitelj', 'village'],
            ['Blagaj', 'village'],
            ['Medjugorje', 'village'],
            ['Jablanica', 'town'],
            ['Stolac', 'town'],
            ['Gradiska', 'town'],
            ['Derventa', 'town'],
            ['Brod', 'town'],
            ['Modrica', 'town'],
            ['Samac', 'town'],
            ['Orasje', 'town'],
            ['Odzak', 'town'],
            ['Drvar', 'town'],
            ['Bosanski Petrovac', 'town'],
            ['Kljuc', 'town'],
            ['Mrkonjic Grad', 'town'],
            ['Sipovo', 'town'],
            ['Kupres', 'town'],
            ['Prozor', 'town'],
            ['Gornji Vakuf-Uskoplje', 'town'],
            ['Donji Vakuf', 'town'],
            ['Novi Travnik', 'town'],
            ['Zepce', 'town'],
            ['Zavidovici', 'town'],
            ['Banovici', 'town'],
            ['Grude', 'town'],
            ['Ljubuski', 'town'],
            ['Citluk', 'town'],
            ['Neum', 'town'],
            ['Srebrenica', 'town'],
            ['Bratunac', 'town'],
            ['Vlasenica', 'town'],
            ['Milici', 'town'],
            ['Sekovici', 'town'],
            ['Han Pijesak', 'village'],
            ['Celinac', 'town'],
            ['Kotor Varos', 'town'],
            ['Laktasi', 'town'],
            ['Srbac', 'town'],
            ['Kozarska Dubica', 'town'],
            ['Novi Grad', 'town'],
            ['Kostajnica', 'town'],
            ['Teslic', 'town'],
            ['Lopare', 'town'],
            ['Ugljevik', 'town'],
            ['Olovo', 'town'],
            ['Breza', 'town'],
            ['Vogosca', 'town'],
            ['Hadzici', 'town'],
            ['Trnovo', 'town'],
            ['Lukomir', 'village'],
            ['Umoljani', 'village'],
            ['Tarcin', 'village'],
            ['Ustikolina', 'village'],
            ['Bileca', 'town'],
            ['Gacko', 'town'],
            ['Visegrad', 'town'],
            ['Rudo', 'town'],
            ['Ljubinje', 'town'],
            ['Berkovici', 'village'],
        ]);
    }

    /**
     * @return array<int, array{0: string, 1: string}>
     */
    private static function serbia(): array
    {
        return self::uniquePlaces([
            ['Beograd', 'city'],
            ['Novi Sad', 'city'],
            ['Nis', 'city'],
            ['Kragujevac', 'city'],
            ['Subotica', 'city'],
            ['Zrenjanin', 'city'],
            ['Pancevo', 'city'],
            ['Cacak', 'city'],
            ['Novi Pazar', 'city'],
            ['Kraljevo', 'city'],
            ['Smederevo', 'city'],
            ['Leskovac', 'city'],
            ['Uzice', 'city'],
            ['Valjevo', 'city'],
            ['Vranje', 'city'],
            ['Sombor', 'city'],
            ['Pozarevac', 'town'],
            ['Pirot', 'town'],
            ['Sabac', 'city'],
            ['Sremska Mitrovica', 'city'],
            ['Loznica', 'town'],
            ['Jagodina', 'town'],
            ['Kikinda', 'town'],
            ['Ruma', 'town'],
            ['Backa Palanka', 'town'],
            ['Vrbas', 'town'],
            ['Gornji Milanovac', 'town'],
            ['Arandjelovac', 'town'],
            ['Prijepolje', 'town'],
            ['Bor', 'town'],
            ['Majdanpek', 'town'],
            ['Topola', 'town'],
            ['Indjija', 'town'],
            ['Stara Pazova', 'town'],
            ['Obrenovac', 'town'],
            ['Mladenovac', 'town'],
            ['Sopot', 'town'],
            ['Kovin', 'town'],
            ['Apatin', 'town'],
            ['Backi Petrovac', 'town'],
            ['Svilajnac', 'town'],
            ['Cuprija', 'town'],
            ['Paracin', 'town'],
            ['Ivanjica', 'town'],
            ['Lajkovac', 'town'],
            ['Bajina Basta', 'town'],
            ['Kosjeric', 'town'],
            ['Guca', 'village'],
            ['Mokra Gora', 'village'],
            ['Kustendorf', 'village'],
            ['Sirig', 'village'],
            ['Krusevac', 'city'],
            ['Prokuplje', 'town'],
            ['Aleksinac', 'town'],
            ['Zajecar', 'town'],
            ['Negotin', 'town'],
            ['Knjazevac', 'town'],
            ['Bela Palanka', 'town'],
            ['Babusnica', 'town'],
            ['Surdulica', 'town'],
            ['Vladicin Han', 'town'],
            ['Bosilegrad', 'town'],
            ['Bujanovac', 'town'],
            ['Presevo', 'town'],
            ['Lebane', 'town'],
            ['Medvedja', 'town'],
            ['Tutin', 'town'],
            ['Sjenica', 'town'],
            ['Nova Varos', 'town'],
            ['Priboj', 'town'],
            ['Pozega', 'town'],
            ['Arilje', 'town'],
            ['Lucani', 'town'],
            ['Trstenik', 'town'],
            ['Vrnjacka Banja', 'town'],
            ['Varvarin', 'town'],
            ['Brus', 'town'],
            ['Kursumlija', 'town'],
            ['Despotovac', 'town'],
            ['Smederevska Palanka', 'town'],
            ['Velika Plana', 'town'],
            ['Petrovac na Mlavi', 'town'],
            ['Golubac', 'town'],
            ['Kladovo', 'town'],
            ['Veliko Gradiste', 'town'],
            ['Ub', 'town'],
            ['Osecina', 'town'],
            ['Krupanj', 'town'],
            ['Ljubovija', 'town'],
            ['Mali Zvornik', 'town'],
            ['Koceljeva', 'town'],
            ['Vladimirci', 'town'],
            ['Sid', 'town'],
            ['Pecinci', 'town'],
            ['Temerin', 'town'],
            ['Becej', 'town'],
            ['Novi Becej', 'town'],
            ['Kanjiza', 'town'],
            ['Senta', 'town'],
            ['Ada', 'town'],
            ['Bela Crkva', 'town'],
            ['Vrsac', 'town'],
            ['Backa Topola', 'town'],
            ['Sremski Karlovci', 'town'],
            ['Titel', 'town'],
            ['Rajac', 'village'],
            ['Ovcar Banja', 'village'],
            ['Trsic', 'village'],
            ['Rudno', 'village'],
            ['Gostusa', 'village'],
        ]);
    }

    /**
     * @return array<int, array{0: string, 1: string}>
     */
    private static function croatia(): array
    {
        return self::uniquePlaces([
            ['Zagreb', 'city'],
            ['Split', 'city'],
            ['Rijeka', 'city'],
            ['Osijek', 'city'],
            ['Zadar', 'city'],
            ['Velika Gorica', 'city'],
            ['Pula', 'city'],
            ['Slavonski Brod', 'city'],
            ['Karlovac', 'city'],
            ['Varazdin', 'city'],
            ['Sibenik', 'city'],
            ['Sisak', 'city'],
            ['Dubrovnik', 'city'],
            ['Bjelovar', 'city'],
            ['Samobor', 'town'],
            ['Vinkovci', 'city'],
            ['Koprivnica', 'city'],
            ['Vukovar', 'city'],
            ['Cakovec', 'city'],
            ['Pozega', 'city'],
            ['Nasice', 'town'],
            ['Makarska', 'town'],
            ['Sinj', 'town'],
            ['Knin', 'town'],
            ['Trogir', 'town'],
            ['Porec', 'town'],
            ['Rovinj', 'town'],
            ['Umag', 'town'],
            ['Labin', 'town'],
            ['Crikvenica', 'town'],
            ['Opatija', 'town'],
            ['Delnice', 'town'],
            ['Gospic', 'town'],
            ['Ogulin', 'town'],
            ['Krapina', 'town'],
            ['Zapresic', 'town'],
            ['Dugo Selo', 'town'],
            ['Kastela', 'town'],
            ['Metkovic', 'town'],
            ['Imotski', 'town'],
            ['Korcula', 'town'],
            ['Hvar', 'town'],
            ['Pag', 'town'],
            ['Nin', 'town'],
            ['Vodice', 'town'],
            ['Biograd na Moru', 'town'],
            ['Cavtat', 'town'],
            ['Trilj', 'town'],
            ['Vrbnik', 'village'],
            ['Kumrovec', 'village'],
            ['Rastoke', 'village'],
            ['Murter', 'village'],
            ['Dakovo', 'city'],
            ['Virovitica', 'town'],
            ['Slatina', 'town'],
            ['Orahovica', 'town'],
            ['Donji Miholjac', 'town'],
            ['Valpovo', 'town'],
            ['Zupanja', 'town'],
            ['Ilok', 'town'],
            ['Otok', 'town'],
            ['Nova Gradiska', 'town'],
            ['Novska', 'town'],
            ['Kutina', 'town'],
            ['Petrinja', 'town'],
            ['Glina', 'town'],
            ['Daruvar', 'town'],
            ['Pakrac', 'town'],
            ['Otocac', 'town'],
            ['Senj', 'town'],
            ['Slunj', 'town'],
            ['Duga Resa', 'town'],
            ['Pazin', 'town'],
            ['Buje', 'town'],
            ['Buzet', 'town'],
            ['Novigrad', 'town'],
            ['Motovun', 'village'],
            ['Bale', 'village'],
            ['Hum', 'village'],
            ['Cres', 'town'],
            ['Mali Losinj', 'town'],
            ['Krk', 'town'],
            ['Rab', 'town'],
            ['Novalja', 'town'],
            ['Supetar', 'town'],
            ['Bol', 'village'],
            ['Stari Grad', 'town'],
            ['Jelsa', 'town'],
            ['Vis', 'town'],
            ['Komiza', 'town'],
            ['Lastovo', 'village'],
            ['Ston', 'town'],
            ['Orebic', 'town'],
            ['Rogoznica', 'town'],
            ['Primosten', 'town'],
            ['Podgora', 'village'],
            ['Baska Voda', 'village'],
            ['Brela', 'village'],
            ['Jezera', 'village'],
            ['Lopar', 'village'],
            ['Plitvicka Jezera', 'settlement'],
            ['Skradin', 'town'],
            ['Benkovac', 'town'],
            ['Obrovac', 'town'],
            ['Drnis', 'town'],
        ]);
    }

    /**
     * @return array<int, array{0: string, 1: string}>
     */
    private static function italy(): array
    {
        return self::uniquePlaces([
            ['Roma', 'city'],
            ['Milano', 'city'],
            ['Napoli', 'city'],
            ['Torino', 'city'],
            ['Palermo', 'city'],
            ['Genova', 'city'],
            ['Bologna', 'city'],
            ['Firenze', 'city'],
            ['Bari', 'city'],
            ['Catania', 'city'],
            ['Venezia', 'city'],
            ['Verona', 'city'],
            ['Messina', 'city'],
            ['Padova', 'city'],
            ['Trieste', 'city'],
            ['Taranto', 'city'],
            ['Brescia', 'city'],
            ['Parma', 'city'],
            ['Modena', 'city'],
            ['Reggio Calabria', 'city'],
            ['Perugia', 'city'],
            ['Ravenna', 'city'],
            ['Rimini', 'city'],
            ['Livorno', 'city'],
            ['Cagliari', 'city'],
            ['Salerno', 'city'],
            ['Ferrara', 'city'],
            ['Siena', 'town'],
            ['Lucca', 'town'],
            ['Pisa', 'city'],
            ['Arezzo', 'town'],
            ['Bergamo', 'city'],
            ['Monza', 'city'],
            ['Como', 'town'],
            ['Lecce', 'city'],
            ['Foggia', 'city'],
            ['Matera', 'town'],
            ['Trento', 'city'],
            ['Bolzano', 'city'],
            ['Udine', 'city'],
            ['Asti', 'town'],
            ['Alba', 'town'],
            ['Sorrento', 'town'],
            ['Positano', 'town'],
            ['Assisi', 'town'],
            ['Orvieto', 'town'],
            ['San Gimignano', 'town'],
            ['Bormio', 'town'],
            ['Cortina d Ampezzo', 'town'],
            ['Taormina', 'town'],
            ['Ravello', 'village'],
            ['Vernazza', 'village'],
            ['Aosta', 'city'],
            ['Ancona', 'city'],
            ['Pesaro', 'town'],
            ['Fano', 'town'],
            ['Ascoli Piceno', 'town'],
            ['Macerata', 'town'],
            ['Pescara', 'city'],
            ['Chieti', 'town'],
            ['Teramo', 'town'],
            ['L Aquila', 'city'],
            ['Campobasso', 'city'],
            ['Potenza', 'city'],
            ['Catanzaro', 'city'],
            ['Cosenza', 'city'],
            ['Siracusa', 'city'],
            ['Ragusa', 'city'],
            ['Trapani', 'city'],
            ['Agrigento', 'city'],
            ['Cefalu', 'town'],
            ['Sassari', 'city'],
            ['Olbia', 'city'],
            ['Nuoro', 'town'],
            ['Oristano', 'town'],
            ['Alghero', 'town'],
            ['Caserta', 'city'],
            ['Benevento', 'town'],
            ['Avellino', 'town'],
            ['Cremona', 'city'],
            ['Pavia', 'city'],
            ['Mantova', 'city'],
            ['Vicenza', 'city'],
            ['Treviso', 'city'],
            ['Belluno', 'town'],
            ['Rovigo', 'town'],
            ['Savona', 'city'],
            ['Imperia', 'town'],
            ['La Spezia', 'city'],
            ['Massa', 'town'],
            ['Carrara', 'town'],
            ['Prato', 'city'],
            ['Pistoia', 'city'],
            ['Grosseto', 'town'],
            ['Viterbo', 'city'],
            ['Latina', 'city'],
            ['Frosinone', 'city'],
            ['Civitavecchia', 'town'],
            ['Alessandria', 'city'],
            ['Novara', 'city'],
            ['Biella', 'town'],
            ['Cuneo', 'city'],
            ['Sanremo', 'town'],
            ['Amalfi', 'town'],
            ['Capri', 'town'],
            ['Ischia', 'town'],
            ['Procida', 'town'],
            ['Monopoli', 'town'],
            ['Ostuni', 'town'],
            ['Gallipoli', 'town'],
            ['Alberobello', 'town'],
            ['Vieste', 'town'],
            ['Gubbio', 'town'],
            ['Spoleto', 'town'],
            ['Portofino', 'village'],
            ['Riomaggiore', 'village'],
            ['Manarola', 'village'],
            ['Corniglia', 'village'],
            ['Monterosso al Mare', 'village'],
            ['Bellagio', 'village'],
            ['Stresa', 'village'],
            ['Erice', 'village'],
        ]);
    }

    /**
     * @return array<int, array{0: string, 1: string}>
     */
    private static function germany(): array
    {
        return self::uniquePlaces([
            ['Berlin', 'city'],
            ['Hamburg', 'city'],
            ['Muenchen', 'city'],
            ['Koeln', 'city'],
            ['Frankfurt am Main', 'city'],
            ['Stuttgart', 'city'],
            ['Duesseldorf', 'city'],
            ['Dortmund', 'city'],
            ['Essen', 'city'],
            ['Leipzig', 'city'],
            ['Bremen', 'city'],
            ['Dresden', 'city'],
            ['Hannover', 'city'],
            ['Nuernberg', 'city'],
            ['Duisburg', 'city'],
            ['Bochum', 'city'],
            ['Wuppertal', 'city'],
            ['Bielefeld', 'city'],
            ['Bonn', 'city'],
            ['Muenster', 'city'],
            ['Karlsruhe', 'city'],
            ['Mannheim', 'city'],
            ['Augsburg', 'city'],
            ['Wiesbaden', 'city'],
            ['Gelsenkirchen', 'city'],
            ['Moenchengladbach', 'city'],
            ['Braunschweig', 'city'],
            ['Chemnitz', 'city'],
            ['Kiel', 'city'],
            ['Aachen', 'city'],
            ['Magdeburg', 'city'],
            ['Freiburg im Breisgau', 'city'],
            ['Mainz', 'city'],
            ['Luebeck', 'city'],
            ['Rostock', 'city'],
            ['Kassel', 'city'],
            ['Potsdam', 'city'],
            ['Erfurt', 'city'],
            ['Regensburg', 'city'],
            ['Ulm', 'city'],
            ['Heidelberg', 'city'],
            ['Wuerzburg', 'city'],
            ['Goettingen', 'city'],
            ['Trier', 'city'],
            ['Passau', 'town'],
            ['Bamberg', 'town'],
            ['Berchtesgaden', 'town'],
            ['Garmisch-Partenkirchen', 'town'],
            ['Rothenburg ob der Tauber', 'town'],
            ['Mittenwald', 'village'],
            ['Binz', 'village'],
            ['Cochem', 'village'],
            ['Saarbruecken', 'city'],
            ['Osnabrueck', 'city'],
            ['Paderborn', 'city'],
            ['Oldenburg', 'city'],
            ['Wolfsburg', 'city'],
            ['Jena', 'city'],
            ['Flensburg', 'town'],
            ['Koblenz', 'city'],
            ['Heilbronn', 'city'],
            ['Pforzheim', 'city'],
            ['Offenbach am Main', 'city'],
            ['Fulda', 'town'],
            ['Siegen', 'city'],
            ['Hagen', 'city'],
            ['Herne', 'city'],
            ['Krefeld', 'city'],
            ['Leverkusen', 'city'],
            ['Solingen', 'city'],
            ['Remscheid', 'city'],
            ['Oberhausen', 'city'],
            ['Moers', 'town'],
            ['Reutlingen', 'city'],
            ['Tuebingen', 'city'],
            ['Konstanz', 'city'],
            ['Ravensburg', 'town'],
            ['Lueneburg', 'town'],
            ['Wilhelmshaven', 'city'],
            ['Bremerhaven', 'city'],
            ['Neubrandenburg', 'city'],
            ['Greifswald', 'city'],
            ['Stralsund', 'city'],
            ['Weimar', 'city'],
            ['Cottbus', 'city'],
            ['Zwickau', 'city'],
            ['Bautzen', 'town'],
            ['Gera', 'city'],
            ['Dessau-Rosslau', 'city'],
            ['Hildesheim', 'city'],
            ['Celle', 'town'],
            ['Hameln', 'town'],
            ['Detmold', 'town'],
            ['Lippstadt', 'town'],
            ['Soest', 'town'],
            ['Ingolstadt', 'city'],
            ['Landshut', 'city'],
            ['Rosenheim', 'city'],
            ['Coburg', 'town'],
            ['Bayreuth', 'city'],
            ['Hof', 'city'],
            ['Aschaffenburg', 'city'],
            ['Lindau', 'town'],
            ['Friedrichshafen', 'city'],
            ['Baden-Baden', 'town'],
            ['Villingen-Schwenningen', 'city'],
            ['Worms', 'city'],
            ['Speyer', 'town'],
            ['Bad Kreuznach', 'town'],
            ['Sankt Goar', 'village'],
            ['Ruedesheim am Rhein', 'town'],
            ['Meersburg', 'village'],
            ['Fuessen', 'town'],
            ['Oberstdorf', 'village'],
            ['Wernigerode', 'town'],
            ['Quedlinburg', 'town'],
            ['Goslar', 'town'],
            ['Ramsau bei Berchtesgaden', 'village'],
            ['Murnau am Staffelsee', 'village'],
            ['Triberg im Schwarzwald', 'village'],
        ]);
    }

    /**
     * @return array<int, array{0: string, 1: string}>
     */
    private static function austria(): array
    {
        return self::uniquePlaces([
            ['Wien', 'city'],
            ['Graz', 'city'],
            ['Linz', 'city'],
            ['Salzburg', 'city'],
            ['Innsbruck', 'city'],
            ['Klagenfurt', 'city'],
            ['Villach', 'city'],
            ['Wels', 'city'],
            ['Sankt Poelten', 'city'],
            ['Dornbirn', 'city'],
            ['Wiener Neustadt', 'city'],
            ['Steyr', 'city'],
            ['Feldkirch', 'city'],
            ['Bregenz', 'city'],
            ['Leonding', 'town'],
            ['Klosterneuburg', 'town'],
            ['Baden', 'town'],
            ['Wolfsberg', 'town'],
            ['Leoben', 'town'],
            ['Krems an der Donau', 'town'],
            ['Traun', 'town'],
            ['Amstetten', 'town'],
            ['Lustenau', 'town'],
            ['Kapfenberg', 'town'],
            ['Moedling', 'town'],
            ['Hall in Tirol', 'town'],
            ['Spittal an der Drau', 'town'],
            ['Kufstein', 'town'],
            ['Schwechat', 'town'],
            ['Tulln an der Donau', 'town'],
            ['Bischofshofen', 'town'],
            ['St. Johann im Pongau', 'town'],
            ['Bad Ischl', 'town'],
            ['Zell am See', 'town'],
            ['Saalbach', 'village'],
            ['Kitzbuehel', 'town'],
            ['Mayrhofen', 'village'],
            ['Seefeld in Tirol', 'village'],
            ['Ischgl', 'village'],
            ['Solden', 'village'],
            ['Eisenstadt', 'city'],
            ['Neusiedl am See', 'town'],
            ['Rust', 'town'],
            ['Melk', 'town'],
            ['Waidhofen an der Ybbs', 'town'],
            ['Zwettl', 'town'],
            ['Lienz', 'town'],
            ['Schladming', 'town'],
            ['Bad Gastein', 'village'],
            ['Mariazell', 'village'],
            ['Heiligenblut', 'village'],
            ['Gmunden', 'town'],
            ['St. Veit an der Glan', 'town'],
            ['Schwaz', 'town'],
            ['Imst', 'town'],
            ['Reutte', 'town'],
            ['Landeck', 'town'],
            ['Saalfelden am Steinernen Meer', 'town'],
            ['Hallein', 'town'],
            ['Tamsweg', 'town'],
            ['Murau', 'town'],
            ['Judenburg', 'town'],
            ['Knittelfeld', 'town'],
            ['Bruck an der Mur', 'town'],
            ['Hartberg', 'town'],
            ['Deutschlandsberg', 'town'],
            ['Voecklabruck', 'town'],
            ['Braunau am Inn', 'town'],
            ['Ried im Innkreis', 'town'],
            ['Perg', 'town'],
            ['Freistadt', 'town'],
            ['Hollabrunn', 'town'],
            ['Mistelbach', 'town'],
            ['Korneuburg', 'town'],
            ['Gloggnitz', 'town'],
            ['Semmering', 'village'],
            ['Neunkirchen', 'town'],
            ['Mattersburg', 'town'],
            ['Oberwart', 'town'],
            ['Bad Tatzmannsdorf', 'village'],
            ['Laa an der Thaya', 'town'],
            ['Retz', 'town'],
            ['Bad Hall', 'town'],
            ['Hallstatt', 'village'],
            ['Alpbach', 'village'],
            ['Pertisau', 'village'],
            ['St. Anton am Arlberg', 'village'],
            ['Lech', 'village'],
            ['Lofer', 'village'],
            ['Werfen', 'village'],
            ['Fuschl am See', 'village'],
            ['Mondsee', 'village'],
            ['Altaussee', 'village'],
            ['Ehrwald', 'village'],
            ['Scharnitz', 'village'],
            ['Bad Hofgastein', 'town'],
            ['Kaprun', 'village'],
            ['Mittersill', 'town'],
        ]);
    }

    /**
     * @return array<int, array{0: string, 1: string}>
     */
    private static function montenegro(): array
    {
        return self::uniquePlaces([
            ['Podgorica', 'city'],
            ['Niksic', 'city'],
            ['Herceg Novi', 'city'],
            ['Budva', 'city'],
            ['Bar', 'city'],
            ['Bijelo Polje', 'city'],
            ['Cetinje', 'city'],
            ['Pljevlja', 'city'],
            ['Ulcinj', 'town'],
            ['Tivat', 'town'],
            ['Berane', 'town'],
            ['Rozaje', 'town'],
            ['Kotor', 'town'],
            ['Danilovgrad', 'town'],
            ['Mojkovac', 'town'],
            ['Kolasin', 'town'],
            ['Plav', 'town'],
            ['Andrijevica', 'town'],
            ['Petnjica', 'town'],
            ['Savnik', 'town'],
            ['Zabljak', 'town'],
            ['Gusinje', 'town'],
            ['Tuzi', 'town'],
            ['Golubovci', 'town'],
            ['Sutomore', 'town'],
            ['Petrovac', 'town'],
            ['Igalo', 'town'],
            ['Risan', 'town'],
            ['Perast', 'town'],
            ['Dobrota', 'town'],
            ['Stoliv', 'village'],
            ['Morinj', 'village'],
            ['Njegusi', 'village'],
            ['Virpazar', 'village'],
            ['Rijeka Crnojevica', 'village'],
            ['Murici', 'village'],
            ['Vranjina', 'village'],
            ['Kumbor', 'village'],
            ['Krasici', 'village'],
            ['Radovici', 'village'],
            ['Grahovo', 'village'],
            ['Crkvice', 'village'],
            ['Biogradska Gora', 'settlement'],
            ['Durmitor', 'settlement'],
            ['Pluzine', 'town'],
            ['Susanj', 'town'],
            ['Donja Lastva', 'village'],
            ['Prcanj', 'village'],
            ['Muo', 'village'],
            ['Orahovac', 'village'],
            ['Lepetani', 'village'],
            ['Zelenika', 'village'],
            ['Baosici', 'village'],
            ['Djenovici', 'village'],
            ['Bijela', 'village'],
            ['Kamenari', 'village'],
            ['Meljine', 'village'],
            ['Njivice', 'village'],
            ['Becici', 'village'],
            ['Rafailovici', 'village'],
            ['Przno', 'village'],
            ['Sveti Stefan', 'village'],
            ['Canj', 'village'],
            ['Dobra Voda', 'village'],
            ['Utjeha', 'village'],
            ['Buljarica', 'village'],
            ['Rezevici', 'village'],
            ['Bigova', 'village'],
            ['Rose', 'village'],
            ['Gornji Stoliv', 'village'],
            ['Godinje', 'village'],
            ['Plavnica', 'village'],
            ['Zabljak Crnojevica', 'village'],
            ['Vusanje', 'village'],
            ['Murino', 'village'],
            ['Lubnice', 'village'],
            ['Matesevo', 'village'],
            ['Trebaljevo', 'village'],
            ['Bioce', 'village'],
            ['Spuz', 'village'],
            ['Martinici', 'village'],
            ['Petrovici', 'village'],
            ['Velika', 'village'],
        ]);
    }

    /**
     * @return array<int, array{0: string, 1: string}>
     */
    private static function northMacedonia(): array
    {
        return self::uniquePlaces([
            ['Skopje', 'city'],
            ['Bitola', 'city'],
            ['Kumanovo', 'city'],
            ['Prilep', 'city'],
            ['Tetovo', 'city'],
            ['Veles', 'city'],
            ['Stip', 'city'],
            ['Ohrid', 'city'],
            ['Gostivar', 'city'],
            ['Strumica', 'city'],
            ['Kavadarci', 'town'],
            ['Kocani', 'town'],
            ['Kicevo', 'town'],
            ['Struga', 'town'],
            ['Gevgelija', 'town'],
            ['Sveti Nikole', 'town'],
            ['Negotino', 'town'],
            ['Delcevo', 'town'],
            ['Kriva Palanka', 'town'],
            ['Radovis', 'town'],
            ['Kratovo', 'town'],
            ['Vinica', 'town'],
            ['Probistip', 'town'],
            ['Berovo', 'town'],
            ['Pehcevo', 'town'],
            ['Resen', 'town'],
            ['Debar', 'town'],
            ['Makedonski Brod', 'town'],
            ['Demir Hisar', 'town'],
            ['Krusevo', 'town'],
            ['Demir Kapija', 'town'],
            ['Bogdanci', 'town'],
            ['Valandovo', 'town'],
            ['Dojran', 'town'],
            ['Krivogastani', 'town'],
            ['Rosoman', 'town'],
            ['Gradsko', 'town'],
            ['Bogovinje', 'town'],
            ['Jegunovce', 'town'],
            ['Tearce', 'town'],
            ['Zelino', 'town'],
            ['Vrapciste', 'town'],
            ['Mavrovo', 'town'],
            ['Rostuse', 'town'],
            ['Centar Zupa', 'town'],
            ['Plasnica', 'town'],
            ['Arachinovo', 'town'],
            ['Ilinden', 'town'],
            ['Petrovec', 'town'],
            ['Sopiste', 'town'],
            ['Studenicani', 'town'],
            ['Cucer Sandevo', 'town'],
            ['Lipkovo', 'town'],
            ['Rankovce', 'town'],
            ['Karbinci', 'town'],
            ['Lozovo', 'town'],
            ['Cesinovo-Oblesevo', 'town'],
            ['Zrnovci', 'town'],
            ['Konce', 'town'],
            ['Bosilovo', 'town'],
            ['Novo Selo', 'town'],
            ['Vasilevo', 'town'],
            ['Mogila', 'town'],
            ['Novaci', 'town'],
            ['Dolneni', 'town'],
            ['Vevcani', 'village'],
            ['Lazaropole', 'village'],
            ['Galicnik', 'village'],
            ['Nizepole', 'village'],
            ['Trpejca', 'village'],
            ['Velestovo', 'village'],
            ['Stenje', 'village'],
            ['Smolari', 'village'],
            ['Meseista', 'village'],
            ['Kanatlarci', 'village'],
            ['Star Dojran', 'village'],
            ['Nov Dojran', 'village'],
            ['Pestani', 'village'],
            ['Labunista', 'village'],
            ['Janche', 'village'],
            ['Brajcino', 'village'],
            ['Vratnica', 'village'],
            ['Matejce', 'village'],
            ['Sredno Konjari', 'village'],
        ]);
    }

    /**
     * @return array<int, array{0: string, 1: string}>
     */
    private static function slovenia(): array
    {
        return self::uniquePlaces([
            ['Ljubljana', 'city'],
            ['Maribor', 'city'],
            ['Celje', 'city'],
            ['Kranj', 'city'],
            ['Koper', 'city'],
            ['Novo Mesto', 'city'],
            ['Velenje', 'city'],
            ['Ptuj', 'city'],
            ['Trbovlje', 'city'],
            ['Kamnik', 'town'],
            ['Jesenice', 'town'],
            ['Nova Gorica', 'city'],
            ['Murska Sobota', 'city'],
            ['Slovenj Gradec', 'town'],
            ['Domzale', 'town'],
            ['Izola', 'town'],
            ['Piran', 'town'],
            ['Postojna', 'town'],
            ['Kocevje', 'town'],
            ['Krsko', 'town'],
            ['Brezice', 'town'],
            ['Sevnica', 'town'],
            ['Grosuplje', 'town'],
            ['Idrija', 'town'],
            ['Ajdovscina', 'town'],
            ['Tolmin', 'town'],
            ['Bovec', 'town'],
            ['Bohinjska Bistrica', 'town'],
            ['Radovljica', 'town'],
            ['Skofja Loka', 'town'],
            ['Litija', 'town'],
            ['Zagorje ob Savi', 'town'],
            ['Hrastnik', 'town'],
            ['Ravne na Koroskem', 'town'],
            ['Dravograd', 'town'],
            ['Lendava', 'town'],
            ['Ormoz', 'town'],
            ['Slovenska Bistrica', 'town'],
            ['Slovenske Konjice', 'town'],
            ['Rogaska Slatina', 'town'],
            ['Sentjur', 'town'],
            ['Medvode', 'town'],
            ['Vrhnika', 'town'],
            ['Logatec', 'town'],
            ['Cerknica', 'town'],
            ['Ilirska Bistrica', 'town'],
            ['Trebnje', 'town'],
            ['Metlika', 'town'],
            ['Crnomelj', 'town'],
            ['Semic', 'town'],
            ['Pivka', 'town'],
            ['Ribnica', 'town'],
            ['Lasko', 'town'],
            ['Zalec', 'town'],
            ['Mozirje', 'town'],
            ['Kranjska Gora', 'town'],
            ['Bled', 'town'],
            ['Portoroz', 'town'],
            ['Ankaran', 'town'],
            ['Sezana', 'town'],
            ['Vipava', 'town'],
            ['Kanal', 'town'],
            ['Kobarid', 'town'],
            ['Most na Soci', 'town'],
            ['Gornja Radgona', 'town'],
            ['Beltinci', 'town'],
            ['Moravske Toplice', 'town'],
            ['Dobrovnik', 'town'],
            ['Sentilj', 'town'],
            ['Dobrovo', 'town'],
            ['Stanjel', 'village'],
            ['Solcava', 'village'],
            ['Jezersko', 'village'],
            ['Smartno', 'village'],
            ['Otocec', 'village'],
            ['Dolenjske Toplice', 'town'],
            ['Rogatec', 'town'],
            ['Preddvor', 'village'],
            ['Cerklje na Gorenjskem', 'town'],
            ['Zrece', 'town'],
            ['Podcetrtek', 'town'],
            ['Bistrica ob Sotli', 'village'],
            ['Kostanjevica na Krki', 'town'],
            ['Miren', 'town'],
        ]);
    }

    /**
     * @param  array<int, array{0: string, 1: string}>  $places
     * @return array<int, array{0: string, 1: string}>
     */
    private static function uniquePlaces(array $places): array
    {
        $unique = [];
        $seen = [];

        foreach ($places as [$name, $type]) {
            $key = strtolower(trim($name));

            if (isset($seen[$key])) {
                continue;
            }

            $seen[$key] = true;
            $unique[] = [$name, $type];
        }

        return $unique;
    }
}
